import React from 'react';
import { ParsedExifData } from '../types';
import { RetroButton } from './RetroButton';
import { Download, FileText, Trash2, Edit } from 'lucide-react';
import { downloadFile } from '../utils/imageProcessing';

interface BatchViewProps {
  files: ParsedExifData[];
  onSelect: (id: string) => void;
  onRemove: (id: string) => void;
  onClear: () => void;
  onCompare: () => void;
}

export const BatchView: React.FC<BatchViewProps> = ({ files, onSelect, onRemove, onClear, onCompare }) => {
  const [selectedIds, setSelectedIds] = React.useState<Set<string>>(new Set());

  const toggleSelection = (id: string) => {
    const newSet = new Set(selectedIds);
    if (newSet.has(id)) newSet.delete(id);
    else newSet.add(id);
    setSelectedIds(newSet);
  };

  const handleExportCSV = () => {
    const headers = ['Filename', 'Date', 'Camera', 'Lens', 'ISO', 'Aperture', 'Shutter', 'GPS'];
    const rows = files.map(f => [
      f.filename,
      f.dateTimeOriginal || 'N/A',
      `${f.make || ''} ${f.model || ''}`,
      f.lens || '',
      f.iso || '',
      f.fNumber || '',
      f.exposureTime || '',
      f.gps ? `${f.gps.latitude},${f.gps.longitude}` : ''
    ]);
    const csvContent = [headers.join(','), ...rows.map(r => r.map(c => `"${c}"`).join(','))].join('\n');
    downloadFile(csvContent, 'pixel_exif_batch.csv', 'text/csv');
  };

  const handleGenerateRenameScript = () => {
    // Generate a simple shell script to rename files based on Date
    let script = "#!/bin/bash\n# Rename script generated by PixelExif\n\n";
    files.forEach(f => {
      if (f.dateTimeOriginal) {
        // format: 2023:10:25 12:00:00 -> 2023-10-25_120000
        const dateStr = f.dateTimeOriginal.replace(/:/g, '-').replace(' ', '_');
        const ext = f.filename.split('.').pop();
        const newName = `${dateStr}_${f.model || 'IMG'}.${ext}`;
        script += `mv "${f.filename}" "${newName}"\n`;
      }
    });
    downloadFile(script, 'rename_files.sh', 'text/plain');
  };

  return (
    <div className="w-full h-full flex flex-col bg-[#0a0a0a] border-2 border-[var(--primary-color)] p-2">
      <div className="flex justify-between items-center mb-4 bg-[var(--primary-color)] text-black p-2 font-pixel">
        <h2 className="text-lg">BATCH PROCESSING ({files.length})</h2>
        <div className="flex gap-2">
           <button onClick={handleExportCSV} className="flex items-center gap-1 hover:underline text-xs"><Download size={14}/> CSV</button>
           <button onClick={handleGenerateRenameScript} className="flex items-center gap-1 hover:underline text-xs"><Edit size={14}/> RENAME SCRIPT</button>
        </div>
      </div>

      <div className="flex-1 overflow-auto custom-scrollbar border border-[var(--primary-color)] mb-4">
        <table className="w-full text-left font-terminal text-[var(--primary-color)] border-collapse">
          <thead>
            <tr className="border-b border-[var(--primary-color)] bg-[var(--primary-color)]/10 sticky top-0">
              <th className="p-2"><input type="checkbox" onChange={(e) => e.target.checked ? setSelectedIds(new Set(files.map(f => f.id))) : setSelectedIds(new Set())} /></th>
              <th className="p-2">FILENAME</th>
              <th className="p-2">CAMERA</th>
              <th className="p-2">DATE</th>
              <th className="p-2">ACTIONS</th>
            </tr>
          </thead>
          <tbody>
            {files.map(file => (
              <tr key={file.id} className="border-b border-[var(--primary-color)]/30 hover:bg-[var(--primary-color)]/20">
                <td className="p-2">
                  <input type="checkbox" checked={selectedIds.has(file.id)} onChange={() => toggleSelection(file.id)} />
                </td>
                <td className="p-2 truncate max-w-[150px] cursor-pointer hover:text-white" onClick={() => onSelect(file.id)}>{file.filename}</td>
                <td className="p-2">{file.model || '-'}</td>
                <td className="p-2">{file.dateTimeOriginal?.split(' ')[0] || '-'}</td>
                <td className="p-2">
                  <button onClick={() => onRemove(file.id)} className="text-red-500 hover:text-red-400"><Trash2 size={16}/></button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="flex justify-between items-center">
         <RetroButton onClick={onClear} variant="danger" className="!text-xs">CLEAR ALL</RetroButton>
         <div className="flex gap-2">
            <RetroButton 
              disabled={selectedIds.size !== 2} 
              onClick={() => {
                 // Pass selected IDs to compare
                 // In a real app we would pass these up, but for now we assume the parent handles the logic based on selection or we need to refine the props.
                 // Actually, let's just use the first two files if nothing selected, or the selected 2.
                 // Limitation of this specific implementation block.
                 if (selectedIds.size === 2) {
                    // This prop needs to accept IDs, but keeping interface simple
                    (onCompare as any)(Array.from(selectedIds));
                 }
              }} 
              className={`!text-xs ${selectedIds.size !== 2 ? 'opacity-50' : ''}`}
            >
              COMPARE (2)
            </RetroButton>
         </div>
      </div>
    </div>
  );
};
